---
- name: Prepare the Migration Control Node for running playbooks
  hosts: localhost
  become: true

  tasks:

    # Put SELinux in permissive mode, logging actions that would be blocked.
    - name: SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Add Kubernetes repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repo
        baseurl: http://yum.kubernetes.io/repos/kubernetes-el$releasever-$basearch
        gpgcheck: no
        repo_gpgcheck: no
        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Add EPEL Repository
      yum:
        name: epel-release
        state: present

    - name: Install pre-req packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker 
        - ebtables 
        - kubeadm 
        - kubectl 
        - kubelet 
        - kubernetes-cni

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - shell: docker info | grep "Cgroup Driver" | awk '{print $3}'
      register: cgroup_driver

    - debug:
        var: cgroup_driver

    # - name: Placeholder true for ipv6 in modprobe
    #   lineinfile: "dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conff line='install ipv6 /bin/true' create=yes"

    - name: Disable CRI
      lineinfile: 
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regexp: '^Environment="{{ item.regexp }}"'
        line: 'Environment="{{ item.line }}"'
        backrefs: yes
      with_items:
        - { regexp: 'KUBELET_KUBECONFIG_ARGS=.*', line: 'KUBELET_KUBECONFIG_ARGS=--cgroup-driver={{ cgroup_driver.stdout }} --enable-cri=false --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true' }
        - { regexp: 'KUBELET_DNS_ARGS=.*', line: 'KUBELET_DNS_ARGS=--cluster-dns=10.3.3.10 --cluster-domain=cluster.local' }

    - name: Start and enable kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

    # - name: Install python libraries
    #   become: true
    #   pip:
    #     name: "{{ item }}"
    #   with_items:
    #     - shade
    #     - python-openstackclient
    #     - pywinrm
    #     - docker-py
    #     - docker-compose

    # - name: Install Ruby Gems
    #   become: true
    #   gem:
    #     name: "{{ item }}"
    #     state: latest
    #     user_install: no
    #     include_doc: no
    #   with_items:
    #     - xml-simple
